Provide SessionStorageNamespaceImpl::ClearData API, test the browser …
mrobinson/brave-core pull request #2
Opened 2020-10-01 18:34 UTC by cathiechen

…side namespace creation, and add more test for navigation scenarios

Resolves 

## Submitter Checklist:

- [ ] Submitted a [ticket](https://github.com/brave/brave-browser/issues) for my issue if one did not already exist.
- [ ] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- Verified that these changes build without errors on
  - [ ] Android
  - [ ] iOS
  - [ ] Linux
  - [ ] macOS
  - [ ] Windows
- Verified that these changes pass automated tests (unit, browser, security tests) on
  - [ ] iOS
  - [ ] Linux
  - [ ] macOS
  - [ ] Windows
- [ ] Verified that all lint errors/warnings are resolved (`npm run lint`)
- [ ] Ran `git rebase master` (if needed).
- [ ] Ran `git rebase -i` to squash commits (if needed).
- [ ] Tagged reviewers and labelled the pull request as needed.
- [ ] Request a security/privacy review as needed.
- [ ] Add appropriate QA labels (QA/Yes or QA/No) to include the closed issue in milestone
- [ ] Public documentation has been updated as necessary. For instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-compatibility-issues-with-tracking-protection
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide

## Test Plan:

## Reviewer Checklist:

- [ ] New files have MPL-2.0 license header.
- [ ] Request a security/privacy review as needed.
- [ ] Adequate test coverage exists to prevent regressions 
- [ ] Verify test plan is specified in PR before merging to source

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on.
- [ ] All relevant documentation has been updated.

2020-10-05 16:16 UTC, mrobinson requested changes
Looks good. I think this just needs a few changes.

2020-10-05 16:16 UTC, mrobinson commented on browser/ephemeral_storage/ephemeral_storage_tab_helper.h
> +  bool DoesEphemeralSessionStorageExist();
It's probably better to rename these to `...ForTesting` and then remove the comment. I think you should also make these static, as they do not need to be called on an instance, but just need access to the static maps. It can look like this:

```c++
  bool URLHasEphemeralLocalStorageForTesting(const GURL& url);
  bool WebContentsHasEphemeralSessionStorageForTesting(WebContents*);
```

2020-10-05 16:16 UTC, mrobinson commented on browser/ephemeral_storage/ephemeral_storage_tab_helper.cc
> +      return;
I think we assume that this is never null, so probably better to add
```
DCHECK(partition);
```
at the start of `EphemeralStorageTabHelper::ClearEphemeralStorageIfNecessary`.

2020-10-05 16:16 UTC, mrobinson commented on browser/ephemeral_storage/ephemeral_storage_tab_helper.cc
> +#include "content/browser/dom_storage/dom_storage_context_wrapper.h"
Is this a layering violation? You should be able to determine this by running `npm run gn_check`. If it is, you'll need to add new api somewhere in the `content/public` directory (such as in `content/public/browser/browser_context.h`) to avoid having to call into the private API here.

2020-10-07 08:55 UTC, cathiechen commented on browser/ephemeral_storage/ephemeral_storage_tab_helper.h
> +  bool DoesEphemeralSessionStorageExist();
Done, thanks!

2020-10-07 08:55 UTC, cathiechen commented on browser/ephemeral_storage/ephemeral_storage_tab_helper.cc
> +      return;
Done!

2020-10-08 11:47 UTC, cathiechen commented on browser/ephemeral_storage/ephemeral_storage_tab_helper.cc
> +#include "content/browser/dom_storage/dom_storage_context_wrapper.h"
Done, thanks!

2020-10-08 13:21 UTC, mrobinson approved these changes
Looks good. I think this could just use a small change before merging.

2020-10-08 13:21 UTC, mrobinson commented on browser/ephemeral_storage/ephemeral_storage_tab_helper.cc
> +    ClearDataInNamespace(partition, session_namespace_id);
I would call this something like `ClearDataInSessionStorageNamespace` since it is in a global namespace.

2020-10-08 16:30 UTC, cathiechen commented on browser/ephemeral_storage/ephemeral_storage_tab_helper.cc
> +    ClearDataInNamespace(partition, session_namespace_id);
Done, thanks!

2020-10-08 17:09 UTC, merged